apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-handler-27125
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-handler-27125
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
